const restaurantData = [
  {
    id: 1,
    name: "Restaurant 1",
    ratings: "4",
    prize: "500",
    offer: "40",
    details: "Description of Restaurant 1",
    menu: [
      { id: 1, name: "IDly", price: 50 },
      { id: 2, name: "Dosai", price: 70 },
      { id: 3, name: "Chicken Briyani", price: 150 },
      { id: 4, name: "Chicken 65", price: 100 },
      { id: 5, name: "Mutton Sukka", price: 200 },
      { id: 6, name: "Idiyappam", price: 60 },
      { id: 7, name: "Egg Podimas", price: 80 },
      { id: 8, name: "Pongal", price: 50 },
      { id: 9, name: "Parotta", price: 40 },
      { id: 10, name: "Fried Rice", price: 120 },
    ],
  },
  {
    id: 2,
    name: "Restaurant 2",
    ratings: "5",
    prize: "200",
    details: "Description of Restaurant 2",
    menu: [
      { id: 1, name: "IDly", price: 45 },
      { id: 2, name: "Dosai", price: 65 },
      { id: 3, name: "Chicken Briyani", price: 130 },
      { id: 4, name: "Chicken 65", price: 90 },
      { id: 5, name: "Mutton Sukka", price: 180 },
      { id: 6, name: "Idiyappam", price: 55 },
      { id: 7, name: "Egg Podimas", price: 75 },
      { id: 8, name: "Pongal", price: 45 },
      { id: 9, name: "Parotta", price: 35 },
      { id: 10, name: "Fried Rice", price: 110 },
    ],
  },
  {
    id: 3,
    name: "Restaurant 3",
    ratings: "4.9",
    prize: "500",
    offer: "60",
    details: "Description of Restaurant 3",
    menu: [
      { id: 1, name: "IDly", price: 55 },
      { id: 2, name: "Dosai", price: 75 },
      { id: 3, name: "Chicken Briyani", price: 160 },
      { id: 4, name: "Chicken 65", price: 110 },
      { id: 5, name: "Mutton Sukka", price: 210 },
      { id: 6, name: "Idiyappam", price: 65 },
      { id: 7, name: "Egg Podimas", price: 85 },
      { id: 8, name: "Pongal", price: 55 },
      { id: 9, name: "Parotta", price: 45 },
      { id: 10, name: "Fried Rice", price: 130 },
    ],
  },
  {
    id: 4,
    name: "Restaurant 4",
    ratings: "4",
    prize: "50",
    offer: "55",
    details: "Description of Restaurant 4",
    menu: [
      { id: 1, name: "IDly", price: 40 },
      { id: 2, name: "Dosai", price: 60 },
      { id: 3, name: "Chicken Briyani", price: 120 },
      { id: 4, name: "Chicken 65", price: 80 },
      { id: 5, name: "Mutton Sukka", price: 160 },
      { id: 6, name: "Idiyappam", price: 50 },
      { id: 7, name: "Egg Podimas", price: 70 },
      { id: 8, name: "Pongal", price: 40 },
      { id: 9, name: "Parotta", price: 30 },
      { id: 10, name: "Fried Rice", price: 100 },
    ],
  },
  {
    id: 5,
    name: "Restaurant 5",
    ratings: "2.9",
    prize: "50",
    offer: "25",
    details: "Description of Restaurant 5",
    menu: [
      { id: 1, name: "IDly", price: 35 },
      { id: 2, name: "Dosai", price: 55 },
      { id: 3, name: "Chicken Briyani", price: 110 },
      { id: 4, name: "Chicken 65", price: 70 },
      { id: 5, name: "Mutton Sukka", price: 140 },
      { id: 6, name: "Idiyappam", price: 45 },
      { id: 7, name: "Egg Podimas", price: 65 },
      { id: 8, name: "Pongal", price: 35 },
      { id: 9, name: "Parotta", price: 25 },
      { id: 10, name: "Fried Rice", price: 90 },
    ],
  },
  {
    id: 6,
    name: "Restaurant 6",
    ratings: "4",
    prize: "500",
    offer: "20",
    details: "Description of Restaurant 6",
    menu: [
      { id: 1, name: "IDly", price: 50 },
      { id: 2, name: "Dosai", price: 70 },
      { id: 3, name: "Chicken Briyani", price: 150 },
      { id: 4, name: "Chicken 65", price: 100 },
      { id: 5, name: "Mutton Sukka", price: 200 },
      { id: 6, name: "Idiyappam", price: 60 },
      { id: 7, name: "Egg Podimas", price: 80 },
      { id: 8, name: "Pongal", price: 50 },
      { id: 9, name: "Parotta", price: 40 },
      { id: 10, name: "Fried Rice", price: 120 },
    ],
  },
];

export default restaurantData;
